//! Build script — embeds vendored community skills into the binary (RFC §4 Option A).
//!
//! Scans `registry/vendored/MANIFEST.toml` + `registry/vendored/<genre>/<id>.md` and
//! emits `OUT_DIR/vendored_catalog.rs`: a static `PresetMeta` array + a
//! `vendored_preset_body(genre, id)` lookup backed by `include_str!` of each file.
//! This lets vendored skills reach a clean installed binary with no runtime disk
//! read, preserving the offline/reproducible invariant. An empty/missing MANIFEST
//! emits an empty catalog (no-op; the build stays green).
//!
//! Runtime override (`vendor_root` / `set_vendor_root_override`) still wins at run
//! time — see `presets::vendored_or_raw` (D6). This codegen is only the fallback
//! path for shipped binaries.

use serde::Deserialize;
use std::env;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
struct Manifest {
    #[serde(default)]
    entries: Vec<Entry>,
}

#[derive(Debug, Deserialize)]
struct Entry {
    skill_id: String,
    genre: String,
    #[serde(default)]
    keywords: Vec<String>,
}

/// One vendored skill, resolved against the source tree (files must exist).
struct Vendored {
    genre: String,
    skill_id: String,
    keywords: Vec<String>,
    body_path: PathBuf,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let vendored_dir = manifest_dir.join("registry").join("vendored");
    let manifest_path = vendored_dir.join("MANIFEST.toml");

    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let mut vendored: Vec<Vendored> = Vec::new();
    if manifest_path.is_file() {
        let raw = fs::read_to_string(&manifest_path).unwrap_or_default();
        let manifest: Manifest = toml::from_str(&raw).unwrap_or(Manifest { entries: vec![] });
        for e in manifest.entries {
            let body_path = vendored_dir
                .join(&e.genre)
                .join(format!("{}.md", e.skill_id));
            if !body_path.is_file() {
                println!(
                    "cargo:warning=vendored manifest references missing file: {} (skipping)",
                    body_path.display()
                );
                continue;
            }
            // Register the body file as a rerun trigger.
            println!("cargo:rerun-if-changed={}", body_path.display());
            vendored.push(Vendored {
                genre: e.genre,
                skill_id: e.skill_id,
                keywords: e.keywords,
                body_path,
            });
        }
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("vendored_catalog.rs");

    fs::write(&out_file, render(&vendored)).expect("write vendored_catalog.rs");
}

fn render(items: &[Vendored]) -> String {
    let mut s = String::new();
    s.push_str("// @generated by build.rs — vendored community skill catalog. DO NOT EDIT.\n");
    s.push_str("// Emitted from registry/vendored/MANIFEST.toml (RFC community-skill-fetch).\n\n");

    // Static catalog (PresetMeta is in scope — this file is include!'d from presets.rs).
    s.push_str("pub static VENDORED_PRESETS: &[PresetMeta] = &[\n");
    for v in items {
        s.push_str(&format!(
            "    PresetMeta {{ genre: Genre::{}, skill_id: {:?}, keywords: {} }},\n",
            genre_variant(&v.genre),
            v.skill_id,
            fmt_keywords(&v.keywords),
        ));
    }
    s.push_str("];\n\n");

    // Body lookup backed by compile-time include_str! of each file (absolute path).
    if items.is_empty() {
        s.push_str(
            "pub fn vendored_preset_body(_genre: Genre, _skill_id: &str) -> Option<&'static str> {\n    None\n}\n",
        );
    } else {
        s.push_str(
            "pub fn vendored_preset_body(genre: Genre, skill_id: &str) -> Option<&'static str> {\n",
        );
        s.push_str("    match (genre, skill_id) {\n");
        for v in items {
            s.push_str(&format!(
                "        (Genre::{}, {:?}) => Some(include_str!({:?})),\n",
                genre_variant(&v.genre),
                v.skill_id,
                v.body_path.to_str().expect("utf-8 path"),
            ));
        }
        s.push_str("        _ => None,\n    }\n}\n");
    }
    s
}

fn genre_variant(s: &str) -> &'static str {
    match s {
        "developer" => "Developer",
        "creator" => "Creator",
        "researcher" => "Researcher",
        "business" => "Business",
        other => {
            println!("cargo:warning=vendored manifest has unknown genre '{other}' (skipping)");
            // Fall through; the caller filters missing files, but an unknown genre
            // still compiles — emit Developer so the row is harmless if reached.
            "Developer"
        }
    }
}

fn fmt_keywords(kw: &[String]) -> String {
    if kw.is_empty() {
        return "&[]".to_string();
    }
    let items: Vec<String> = kw.iter().map(|k| format!("{:?}", k)).collect();
    format!("&[{}]", items.join(", "))
}
